# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import demo_pb2 as demo__pb2


class DemoServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateOne = channel.unary_unary(
        '/demo.DemoService/CreateOne',
        request_serializer=demo__pb2.RequestData.SerializeToString,
        response_deserializer=demo__pb2.ResponseData.FromString,
        )
    self.DeleteOne = channel.unary_unary(
        '/demo.DemoService/DeleteOne',
        request_serializer=demo__pb2.RequestData.SerializeToString,
        response_deserializer=demo__pb2.ResponseData.FromString,
        )
    self.TransferOne = channel.unary_unary(
        '/demo.DemoService/TransferOne',
        request_serializer=demo__pb2.RequestData.SerializeToString,
        response_deserializer=demo__pb2.ResponseData.FromString,
        )
    self.GetCreateNotify = channel.unary_unary(
        '/demo.DemoService/GetCreateNotify',
        request_serializer=demo__pb2.RequestData.SerializeToString,
        response_deserializer=demo__pb2.ResponseData.FromString,
        )


class DemoServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateOne(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteOne(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TransferOne(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCreateNotify(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DemoServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateOne': grpc.unary_unary_rpc_method_handler(
          servicer.CreateOne,
          request_deserializer=demo__pb2.RequestData.FromString,
          response_serializer=demo__pb2.ResponseData.SerializeToString,
      ),
      'DeleteOne': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteOne,
          request_deserializer=demo__pb2.RequestData.FromString,
          response_serializer=demo__pb2.ResponseData.SerializeToString,
      ),
      'TransferOne': grpc.unary_unary_rpc_method_handler(
          servicer.TransferOne,
          request_deserializer=demo__pb2.RequestData.FromString,
          response_serializer=demo__pb2.ResponseData.SerializeToString,
      ),
      'GetCreateNotify': grpc.unary_unary_rpc_method_handler(
          servicer.GetCreateNotify,
          request_deserializer=demo__pb2.RequestData.FromString,
          response_serializer=demo__pb2.ResponseData.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'demo.DemoService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
